CREATE TABLE `users` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`password` VARCHAR(34) NOT NULL COLLATE 'utf8_bin',
	`status` TINYINT(2) NOT NULL,
	`last_ip` VARCHAR(40) NOT NULL COLLATE 'utf8_bin',
	`last_login` DATETIME NOT NULL,
	`created` DATETIME NOT NULL,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;
